# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argocdf < Formula
  desc "ArgoCD Diff Tool - show manifest diffs for ArgoCD apps affected by a PR"
  homepage "https://github.com/rgeraskin/argocdf"
  version "0.4.1"
  license "MIT"

  depends_on "helm"
  depends_on "kustomize"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgeraskin/argocdf/releases/download/v0.4.1/argocdf_Darwin_x86_64.tar.gz"
      sha256 "9ec835d60be9128f40102cbe12c72774524d91c331fdd10714caa4790d4ff865"

      define_method(:install) do
        bin.install "argocdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgeraskin/argocdf/releases/download/v0.4.1/argocdf_Darwin_arm64.tar.gz"
      sha256 "cf10f78237166e9bb79ff734713b60dbfa2eb889991739b55c3bdffffee2dbde"

      define_method(:install) do
        bin.install "argocdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/argocdf/releases/download/v0.4.1/argocdf_Linux_x86_64.tar.gz"
      sha256 "e66107627581d66fa8e379995cd66f9578da2c170913d8ae8aa18229732593ce"
      define_method(:install) do
        bin.install "argocdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/argocdf/releases/download/v0.4.1/argocdf_Linux_arm64.tar.gz"
      sha256 "7f525ac36a837563dbd6f99f2cf20444d81e48e15ae3fc741e665ecc76b35364"
      define_method(:install) do
        bin.install "argocdf"
      end
    end
  end
end
