# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsssologin < Formula
  desc "AWS SSO Login Headless Automation"
  homepage "https://github.com/rgeraskin/awsssologin"
  version "0.4.0"
  license "MIT"

  depends_on "awscli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgeraskin/awsssologin/releases/download/v0.4.0/awsssologin_Darwin_x86_64.tar.gz"
      sha256 "f88a1579ea0f474408abf70e70492557a9c16bbec0a71a482eff84bc05df7a35"

      define_method(:install) do
        bin.install "awsssologin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgeraskin/awsssologin/releases/download/v0.4.0/awsssologin_Darwin_arm64.tar.gz"
      sha256 "65135cc8896bbd69d062169bb65b6219b53a476c2a3a989b66f0fb4f208b4c92"

      define_method(:install) do
        bin.install "awsssologin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/awsssologin/releases/download/v0.4.0/awsssologin_Linux_x86_64.tar.gz"
      sha256 "2b0f14b4f595057ce9f001a30f1bd2c203a65d16f26dd87f533597e2ce0d9b66"
      define_method(:install) do
        bin.install "awsssologin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/awsssologin/releases/download/v0.4.0/awsssologin_Linux_arm64.tar.gz"
      sha256 "f2153af587dde4d7b83364bd52d04b5b4460119755dd5f987a71d189e04ec89f"
      define_method(:install) do
        bin.install "awsssologin"
      end
    end
  end
end
