# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godiffyaml < Formula
  desc "Human-readable diffs for yamls with multiple documents"
  homepage "https://github.com/rgeraskin/godiffyaml"
  version "0.1.0"
  license "MIT"

  depends_on "difftastic"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgeraskin/godiffyaml/releases/download/v0.1.0/godiffyaml_Darwin_x86_64.tar.gz"
      sha256 "c2ba87002317cd96865cccd970ee519ab1931b6738d78253865a8519ca645635"

      def install
        bin.install "godiffyaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgeraskin/godiffyaml/releases/download/v0.1.0/godiffyaml_Darwin_arm64.tar.gz"
      sha256 "8bcac963493def96183b364459419d34dffe58ee6e3c02d0dad985a737a274bb"

      def install
        bin.install "godiffyaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/godiffyaml/releases/download/v0.1.0/godiffyaml_Linux_x86_64.tar.gz"
      sha256 "b6a4f738d2cb7639393bd8abf5b7a5c124a472e79fc17f7164f91a822b321520"
      def install
        bin.install "godiffyaml"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rgeraskin/godiffyaml/releases/download/v0.1.0/godiffyaml_Linux_arm64.tar.gz"
      sha256 "c036014179e9a74c893246552779e446244bc1d22e4b50c424fff9e6e985ffe9"
      def install
        bin.install "godiffyaml"
      end
    end
  end
end
