# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kctouch < Formula
  desc "A cli tool for managing macOS Keychain items with TouchID authentication"
  homepage "https://github.com/rgeraskin/kctouch"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rgeraskin/kctouch/releases/download/v0.2.0/kctouch_Darwin_x86_64.tar.gz"
    sha256 "823f303f7df1a1c6b6ab7fbdb527a63e0e332f297af531d9c9499251b4d8bd64"

    define_method(:install) do
      bin.install "kctouch"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rgeraskin/kctouch/releases/download/v0.2.0/kctouch_Darwin_arm64.tar.gz"
    sha256 "cafd1f5f13e9b4b27c92e4d438c87afb3877e0e3b19d7b1d84c311f0d4c7de9a"

    define_method(:install) do
      bin.install "kctouch"
    end
  end
end
