# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kctouch < Formula
  desc "A cli tool for managing macOS Keychain items with TouchID authentication"
  homepage "https://github.com/rgeraskin/kctouch"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/rgeraskin/kctouch/releases/download/v0.1.0/kctouch_Darwin_x86_64.tar.gz"
    sha256 "2b879dcc32b18e60ddb64916f3505cd905a22c5c1f0ab9051baf6da6627cec1b"

    def install
      bin.install "kctouch"
    end
  end
  on_arm do
    url "https://github.com/rgeraskin/kctouch/releases/download/v0.1.0/kctouch_Darwin_arm64.tar.gz"
    sha256 "8c55b24418623928b21ca9814514a7fa5d2ca44e48dee98ffb4b6468d5e25b40"

    def install
      bin.install "kctouch"
    end
  end
end
